#!/bin/bash

mkdir -p public/models

if [[ ! -d "node_modules" ]]; then
    npm ci
fi

if [[ ! -d "venv" ]]; then
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
else
    source venv/bin/activate
    hf download --local-dir public/models/Xenova/vit-gpt2-image-captioning/ "Xenova/vit-gpt2-image-captioning"
fi